name: rideonline_client
description: A new Flutter project.
publish_to: 'none'
version: 0.2.19+19

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  http_interceptor: ^2.0.0-beta.6
  flutter_svg: ^1.1.6
  go_router: ^6.0.1
  lottie: ^2.2.0
  flutter_multi_formatter: ^2.10.2
  curved_navigation_bar: ^1.0.3
  adaptive_navigation: ^0.0.7
  flutter_map: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  infinite_scroll_pagination: ^3.2.0
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: source-assets/app.png

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/animation/
